version: '3.8'

services:
  # Servicio de PHP con Apache (usando el Dockerfile)
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: producto2_php_apache
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./apache/default.conf:/etc/apache2/sites-available/000-default.conf
    networks:
      - producto2_network

  # Servicio de MySQL
  db:
    image: mysql:8.0
    container_name: producto2_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: producto2_db
      MYSQL_USER: producto2_user
      MYSQL_PASSWORD: producto2_password
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - producto2_network

  # Servicio de phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: producto2_phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    networks:
      - producto2_network

# Red personalizada para los contenedores
networks:
  producto2_network:
    driver: bridge

